timing:
  max_steps: 550000

data:
  name: deepfix-style
  task: err-compiler
  splits:
    train:
      format: substitute
      paths: [/root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin0/*/*,
              /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin1/*/*,
              /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin2/*/*,
              /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin3/*/*,
              /root/data/err-data-compiler--auto-corrupt--codeforce--deepfix-style/*/*.json]
      shuffle: true
      big_files: ../data/programs_with_line_of_length_over_80toks.txt
    dev:
      format: vanilla
      path: /root/data/err-dev-compiler--for-deepfix/err-dev.2000.jsonl
    test:
      format: vanilla
      path: /root/data/err-dev-compiler--for-deepfix/err-dev.2000.jsonl
  vocab:
    path: /root/data/err-vocab-compiler--for-deepfix/combined.vocab
    min_freq: 2

train:
  batch_size: 20
