timing:
  max_steps: 150000

data:
  name: deepfix-style
  task: err-compiler
  splits:
    train:
      format: substitute
      paths: [ /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin0/*/*,
               /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin1/*/*,
               /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin2/*/*,
               /root/data/err-data-compiler--auto-corrupt--orig-deepfix/bin3/*/* ]
      shuffle: true
    dev:
      format: vanilla
      path: /root/data/err-dev-compiler--for-deepfix/err-dev.2000.jsonl
    test:
      format: vanilla
      path: /root/data/err-dev-compiler--for-deepfix/err-dev.2000.jsonl
  vocab:
    path: /root/data/err-vocab-compiler--for-deepfix/combined.vocab
    min_freq: 2
